# Generated by Django 5.0 on 2023-12-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expirationDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transactionDate',
            field=models.DateField(),
        ),
    ]
