# Generated by Django 5.0 on 2023-12-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_expirationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=15.5, max_digits=10),
            preserve_default=False,
        ),
    ]
